name = "passkey4s"
main = "../out/worker/fastLinkJS.dest/main.js"
compatibility_date = "2026-05-25"

[vars]
RP_ID = "localhost"
ORIGIN = "http://localhost:18787"

[[durable_objects.bindings]]
name = "USER_DO"
class_name = "UserDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserDurableObject"]
